WIP: modal_errors: Limit the number of locations shown for an error
open-contracting/cove-ocds pull request #65
Opened 2020-09-14 13:27 UTC by Bjwebb

#59

2020-09-14 17:18 UTC, Bjwebb commented
![](https://github.trello.services/images/mini-trello-icon.png) [Limit JSON paths shown for validation errors if there are lots](https://trello.com/c/9ZHuauJF/91-limit-json-paths-shown-for-validation-errors-if-there-are-lots)

2020-09-29 14:41 UTC, odscjames requested changes

2020-09-29 14:41 UTC, odscjames commented on cove_ocds/tests_functional.py
> +    Check that when there are less than 100 error locations, they are all shown
less than **1000**?

2020-09-29 14:41 UTC, odscjames commented on cove_ocds/tests_functional.py
> +    Check that when there are less than 100 error locations, they are all shown
1000?

2020-09-29 15:09 UTC, odscjames approved these changes

2020-09-29 15:19 UTC, merged